### PR TITLE
Fix TreeUtils.visit() to recurse into subtrees correctly

### PR DESCRIPTION
**Pull request by blizzy78**
Hi,

I've fixed TreeUtils.visit() so that it recurses into subtrees correctly. Before the fix it would never notice when tree traversal had exited a subtree, resulting in wrong parameters passed to the visitor. I've also modified the test so that it tests against this.

Cheers,

Maik

### CODE REVIEW

**Comment by blizzy78** [comment]
Looks like I broke passing ObjectIds to the visitor. I've fixed that and added code to the test.

**Comment by kevinsawicki** [comment]
Thank you so much for this, I have merged it into master as commit 87692ae68d20675d2a52916195e85816d5c8e089.

I made a few formatting tweaks and squashed the two commits but other than that the change looked good and again, thank you for it.

I plan on releasing the 1.0 of this library soon so if you run into any other issues or have any feature requests, please let me know.

**Comment by flapouille** [comment]
Hi, has there been a release including that change ? I am running into the same problem... Thanks

**Comment by flapouille** [comment]
Hi, has there been a release including that change ? I am running into the same problem... Thanks

**Comment by kevinsawicki** [comment]
This has not been released, this library isn't really active anymore, I no longer work on it, you might want to fork it and publish your own version to maven central if you need this.

**Comment by flapouille** [comment]
It's a shame because that library was very user friendly and that patch was already developped .. It would be a good idea to specify when the library is deprecated , unless I haven't seen where it was mentioned...

**Comment by kevinsawicki** [comment]
Sorry about that, it should be communicated more clearly, I'll update the README.

**Pull request closed without merging**
